### ISSUE TITLE
Python 3 - Ordered Dictionary

### ISSUE THREAD

**Issue by schickling** [udacity/ud120-projects#12]
I've ported this repo over to python 3 but facing an issue for the mini project of lesson 6.
It seems that when I'm importing the data it comes in an arbitrary order, what means I can't compute the wanted values in the quizzes.

Is there something I can do about it?

**Comment by ShengKungYi** [comment]
Sorry for the long delay in response! We've added a file to the tools folder with the key order as in Python 2, you can modify the feature_format.py file in order to implement the fix to maintain compatibility between Python versions to complete assignments.
