### ISSUE TITLE
database download error fix by your hand

### ISSUE THREAD

**Issue by trotsky1997** [udacity/ud120-projects#121]
in file ./tools/startup.py
at line 34,line 35,line 44
change stream "**enron_mail_20150507.tgz**" to "**enron_mail_20150507.tar.gz**"
save and run the startup.py
now,it's work!
my name is leifeng~

__________________________________________________________
issues' reason:guys of enron_mails have changed their compress file format( also the download URL),but udacity have not refresh and change their code.

**Comment by UnicornTear** [comment]
XieXie LeiFeng ^0^

**Comment by Dynamic-Gravity** [comment]
I just used this last week and it worked fine. Did they _just_ change the link? And tgz and tar.gz are the same format, just another way of naming a tarball.

**Comment by ShengKungYi** [comment]
Thanks for the catch, looks like this must have just happened recently. There was a pull request with this fix, so it's been merged in.

**Comment by AKS94** [comment]
i have downloaded the zip file manually but i am not able to unzip it, but i get a error that the file appears to be a invalid archive.
