### ISSUE TITLE
Cannot download enron_mail_20150507.tgz

### ISSUE THREAD

**Issue by iselind** [udacity/ud120-projects#126]
The link in startup.py, https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tgz doesn't work so i cannot download the enron data. All i get is HTTP Error 404 Document not found.

**Comment by 0prototype** [comment]
Hi, my startup.py file contains different link and it is working, so try it.
https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tar.gz

**Comment by iselind** [comment]
Great, so cherry-picking 8f7c1060a106bca522db6ec6a6c7f64c0a835824 should resolve it then?

**Comment by 0prototype** [comment]
Yep, definitely.

**Comment by iselind** [comment]
Awesome, thanks a lot!
