### ISSUE TITLE
Relative Paths Are Broken

### ISSUE THREAD

**Issue by CaldwellYSR** [udacity/ud120-projects#142]
I've been getting in import error when trying to import preprocess and it's stopping me from moving forward with the Naive Bayes mini project. I hardcoded it and got the following error message 

```
Traceback (most recent call last):                  
  File "naive_bayes/nb_author_id.py", line 22, in <module>                                               
    features_train, features_test, labels_train, labels_test = preprocess()                              
  File "/home/caldwellysr/Documents/Udacity/MachineLearning/ud120-projects/tools/email_preprocess.py", line 32, in preprocess                                                                                      
    authors_file_handler = open(authors_file, "r")  
IOError: [Errno 2] No such file or directory: '../tools/email_authors.pkl'
```

**Comment by CaldwellYSR** [comment]
Turns out to be a non issue. It was more about me not knowing Python as well as I thought. The relative paths weren’t working because my working directory was the root of the repo not the naive_bayes folder.

**Comment by ShaikhaV** [comment]
Hi CaldwellYSR,
I'm facing same issue, could you please elaborate more on this problem and what did you do to fix it?

Shaikha

**Comment by CaldwellYSR** [comment]
cd into the directory where your python file is. In this case for me it was the naive_bayes directory.

**Comment by ShaikhaV** [comment]
Thank you!

**Comment by ketozhang** [comment]
Relative paths are usually a bad idea to distribute as a program. Often times the solutions is to append `sys.path` with the absolute path of where the python file lives `__file__` and then navigating to the correct path. I like the solution in Python 3 (uses pathlib's resolve function) but sadly Udacity still sticks to Python 2.
