### ISSUE TITLE
No such file or directory: 'word_data_overfit.pkl'

### ISSUE THREAD

**Issue by nmb10** [udacity/ud120-projects#2]
Hi.
In the feature_selection mini project there are  [imports](https://github.com/udacity/ud120-projects/tree/master/feature_selection) of word_data_overfit.pkl and email_authors_overfit.pkl, but there are no such files. 
How to get those files?
Thank you.

**Comment by ShengKungYi** [comment]
Looks like these samples files are now in the folder, but also note that the files that are now being referenced are those in a different folder, and created in an earlier part of the course.
