### ISSUE TITLE
ImportError: No module named numpy

### ISSUE THREAD

**Issue by adamUpchurch** [udacity/ud120-projects#233]
### What is the issue?

I am unable to run the script `nb_author_id.py` -- I am receiving a 'ImportError: No module named nump'

### Did you try recovering your dependencies?

I am unfamiliar with how to recover dependencies

### Environment
```
System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz

Python 2.7.14

Package      Version
------------ -------
joblib       0.13.2 
numpy        1.16.3 
pip          19.1.1 
scikit-learn 0.21.1 
scipy        1.2.1  
setuptools   41.0.1 
sklearn      0.0    
wheel        0.33.4 
```

### Steps to Reproduce

`python2 nb_author_id.py` 
^from the naive_bayes folder

### Expected Behavior

Run the script and get prediction accuracy

### Actual Behavior

```
AdamMacPro naive_bayes $ python2 nb_author_id.py
Traceback (most recent call last):
  File "nb_author_id.py", line 16, in <module>
    from email_preprocess import preprocess
  File "../tools/email_preprocess.py", line 5, in <module>
    import numpy
ImportError: No module named numpy
```

**Comment by adamUpchurch** [comment]
So, I solved the numpy issue by running:
```
python2.7 -m pip install numpy
```
I had to do the same for sklearn.

I ran into a subsequence error
```
Traceback (most recent call last):
  File "nb_author_id.py", line 16, in <module>
    from email_preprocess import preprocess
  File "../tools/email_preprocess.py", line 7, in <module>
    from sklearn import cross_validation
ImportError: cannot import name cross_validation
```

In order to fix this:
in email_preprocess.py, replace line 7 with:
`from sklearn.model_selection import train_test_split`

& replace line 42 with:
`features_train, features_test, labels_train, labels_test = train_test_split(word_data, authors, test_size=0.1, random_state=42)`

**Comment by pshobha97** [comment]
do i need to install nltk?

**Comment by garimasharma4** [comment]
@pshobha97 yes you do.

Have you finished this course (Intro to Machine Learning) or still enrolled? I enrolled just a month back and would like to join a study group if there is any or make one?
