### ISSUE TITLE
UD120 references to UD421

### ISSUE THREAD

**Issue by mikezawitkowski** [udacity/ud120-projects#25]
I noticed in the headline that the repository reference UD421, reads:

`Starter project code for students taking Udacity ud421`

(See attached screenshot to see what I saw) 
![screenshot 2015-09-30 16 19 35](https://cloud.githubusercontent.com/assets/773195/10209419/f5eef006-678f-11e5-9796-6dffd6514b0f.png)

I believe UD421 is the "iOS Networking with Swift" course, not the "Intro to Machine Learning" course that this is meant to be. It was a little confusing at first, but it's a really simple fix, if you have the right rights.

If someone who has admin rights to this repo were to just go to https://github.com/udacity/ud120-projects then there should be an "edit" button to the immediate right of the text: "Starter project code for students taking Udacity ud421" and you can just change the numbers 421 to 120 and be done! That should result in a little less confusion here.

Thanks so much for making this repository available!

**Comment by ShengKungYi** [comment]
Thanks for the notice! We've made the change to the header line.
