### ISSUE TITLE
Py 2 not Py3

### ISSUE THREAD

**Issue by animenon** [udacity/ud120-projects#30]
Why isn't py3 used?
All scripts are Py2.

**Comment by sergiubuciumas** [comment]
This is not an issue, you can convert easy all code to py3 https://docs.python.org/2/library/2to3.html 
The course is for learning and if you want fully master topics you can modify on your own the code.

**Comment by animenon** [comment]
ok.. :+1: 
 For others reference, steps to convert py2 to 3 :
Goto python3 install>tools>scripts and run from cmd
python 2to3.py --output-dir=<py2_code_dir> -W -n <py3_code_to_be_saved_dir>
