### ISSUE TITLE
Data in final dataset is not correct

### ISSUE THREAD

**Issue by j-bennet** [udacity/ud120-projects#34]
There is bad data in final dataset pickle. Some of the records do not match data in `enron61702insiderpay.pdf`. For example see the record for `BELFER ROBERT` in pdf:

https://www.dropbox.com/s/423oieglmhpmhxd/Screenshot%202016-03-08%2021.36.43.png?dl=0

And in dataset:

```
import pickle
from pprint import pprint
with open("final_project_dataset.pkl", "r") as data_file:
    data_dict = pickle.load(data_file)

pprint(data_dict['BELFER ROBERT'])
# OUT: {'bonus': 'NaN',
# OUT:  'deferral_payments': -102500,
# OUT:  'deferred_income': 'NaN',
# OUT:  'director_fees': 3285,
# OUT:  'email_address': 'NaN',
# OUT:  'exercised_stock_options': 3285,
# OUT:  'expenses': 'NaN',
# OUT:  'from_messages': 'NaN',
# OUT:  'from_poi_to_this_person': 'NaN',
# OUT:  'from_this_person_to_poi': 'NaN',
# OUT:  'loan_advances': 'NaN',
# OUT:  'long_term_incentive': 'NaN',
# OUT:  'other': 'NaN',
# OUT:  'poi': False,
# OUT:  'restricted_stock': 'NaN',
# OUT:  'restricted_stock_deferred': 44093,
# OUT:  'salary': 'NaN',
# OUT:  'shared_receipt_with_poi': 'NaN',
# OUT:  'to_messages': 'NaN',
# OUT:  'total_payments': 102500,
# OUT:  'total_stock_value': -44093}
```

Comparing numbers:

field | pdf | dataset
------|------|-----
deferred income | -102500 | NaN
deferral payments |  - | -102500 
expenses | 3285 | NaN
exercised stock options | - | 3285
restricted stock | 44093 | NaN
restricted stock deferred | -44093 | 44093
total stock value | - | -44093

**Comment by ShengKungYi** [comment]
Yes, this is a known issue with the dataset. Unfortunately, with the dependencies of the repository files to quizzes within the corresponding course, there are currently no plans on revising the dataset. For the purposes of the final project for the course, you are encouraged to make the necessary corrections to data points like this one as part of your data cleaning process.
