### ISSUE TITLE
Miniproject 11: parse_out_email_text.py initial code begins with the stemmer

### ISSUE THREAD

**Issue by mathpunk** [udacity/ud120-projects#36]
In the **Warming Up with parseOutText()** part of the mini-project, I was frustrated to find that following the instructions, which gave me the text, "hi everyon if you can read this messag your proper use parseouttext pleas proceed to the next part of the project", resulted in a wrong answer. 

I moved on to the next subproject and learned that I was supposed to augment the function with a stemmer. So, I suspect that a pull request by someone who had already completed that part of the project accidentally got merged.

**Comment by ShengKungYi** [comment]
Which files did you find with the stemmer already implemented? I can see that the repository version of `/tools/parse_out_email_text.py` imports the SnowballStemmer but doesn't actually implement it.

**Comment by mathpunk** [comment]
I found it in that very file, at
commit 18d18aea0a3c2fd39e05ec22b7c37a4f685d99d8

**Comment by ShengKungYi** [comment]
That looks like work performed by a student working on the course material, and not part of the main repository. The change history on the master branch only shows a couple of changes, and neither of them have to do with the Stemmer. Did anything else seem off when you were working on things in the course?

**Comment by mathpunk** [comment]
Not so far, but I jumped in at text processing. I'm backtracking now to get
introduced to the Enron data. Did I somehow clone the wrong repo?

**Comment by ShengKungYi** [comment]
That would be my best guess. You might need to start fresh, since it does sound like you've gotten a branch or fork with work already filled in. I'll close the issue for now, but follow up if you're still having trouble getting the project materials.

**Comment by mathpunk** [comment]
I made certain the repo I cloned this time was the Udacity official one --
I think I must have cloned some student's version.

But, I have come across something weird, and a co-worker going through
these exercises had the same problem: we cannot find the Enron PCA code
example, only the eigenface one. The video has a "doPCA" function visible;
I grepped for that string and I couldn't find any results.

**Comment by ShengKungYi** [comment]
Good to hear that you were able to get the correct repository downloaded.

In regards to the PCA code, you are correct that the Enron PCA code is not included in the project repository. Not all of the code shown in the course videos is included in the repository, it is primarily only the code that you will be working with in the course's mini-projects and final project. Hopefully that clarifies things!
