### ISSUE TITLE
featureFormat remove_any_zeroes=False returns 0 records.

### ISSUE THREAD

**Issue by aaghi** [udacity/ud120-projects#4]
The following if statement   -
 if remove_all_zeroes:
            all_zeroes = True
            for item in tmp_list:
                if item != 0 and item != "NaN":
                    append = True
Is missing an else clause 
else:
    append = True

**Comment by ShengKungYi** [comment]
Functionality for remove_all_zeroes and remove_any_zeroes appear to have been updated.
