### ISSUE TITLE
Was Enron emails directory removed  from tools/.  ?? 

### ISSUE THREAD

**Issue by gaurav1212** [udacity/ud120-projects#5]
I am unable to find the enron_mail_20110402/ directory in this repo.  
The code from text_learning is bugging due to this.  :(
Was that directory removed ? Is it available somewhere else ? 

-Gaurav

**Comment by cmmalone** [comment]
Hi Gaurav1212,

The Enron emails repo should be downloaded directly from the internet, it’s not in the git repository (it’s very large).  The startup script will automatically do this for you when you run it (see the Lesson 1 Naive Bayes mini-project for instructions on getting/running that script) or else you can use this link:

https://www.cs.cmu.edu/~./enron/ <https://www.cs.cmu.edu/~./enron/>

Katie

**Comment by gaurav1212** [comment]
Hi cmmalone, 

Wow!!  a reply in 15 mins :).   You are awsome !!  :+1:  
Thank you!, and Happy New Year  !!!

-Gaurav

**Comment by cmmalone** [comment]
no problem, happy new year to you too!
