### ISSUE TITLE
ImportError: No module named email_preprocess 

### ISSUE THREAD

**Issue by abhiteshdas** [udacity/ud120-projects#50]
%run "/home/abhiteshd/Documents/Abhitesh _docs/Abhitesh/BITS/Semester-4 (June 2016)/udacity/projects/naive_bayes/nb_author_id.py"
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/abhiteshd/Documents/Abhitesh _docs/Abhitesh/BITS/Semester-4 (June 2016)/udacity/projects/naive_bayes/nb_author_id.py in <module>()
     14 from time import time
     15 sys.path.append("../tools/")
---> 16 from email_preprocess import preprocess
     17 
     18 

ImportError: No module named email_preprocess 

Editor used: Canopy
OS: Ubuntu

Please help. Thanks :)

**Comment by ShengKungYi** [comment]
Looks like this got solved, based on the conversation on the other issue. Closing this one!
