### ISSUE TITLE
_pickle.UnpicklingError: the STRING opcode argument must be quoted

### ISSUE THREAD

**Issue by AbT10** [udacity/ud120-projects#65]
line 37 un email_preprocess.py file. i'm on python 3.5. I'm using pickle to load the file where it reports the error. 

![capture4](https://cloud.githubusercontent.com/assets/15520739/20352437/4a78f8e0-ac3d-11e6-8c35-c5f8d92d0faf.PNG)

**Comment by zhililab** [comment]
I got this problem too. Did anyone have fixed that?

**Comment by kingsman142** [comment]
+1

**Comment by nit-esh** [comment]
+1

**Comment by Bhavese** [comment]
+1
