### ISSUE TITLE
Feature_format

### ISSUE THREAD

**Issue by leandrobbraga** [udacity/ud120-projects#66]
There is no such module when I try to run this code. What can I do?

**Comment by ShengKungYi** [comment]
Which script are you talking about and from which folder are you running it? It sounds like your issue might be related to #13. Please provide more details if you continue to run into issues.

**Comment by AliciaDapplications** [comment]
I am having the same issue and I have checked that the program is directing to the correct path.

**Comment by photom** [comment]
I have had a same issue when running k_means_cluster.py at root directory.
I can solved by changing current working directory to k_means.
`$ cd k_means`
`$ python k_means_cluster.py`
