### ISSUE TITLE
module 'urllib' has no attribute 'urlretrieve'

### ISSUE THREAD

**Issue by venkicnu** [udacity/ud120-projects#86]
Hi,

When i am trying to run startup.py script under tools folder, it is throwing below exception.

Exception: module 'urllib' has no attribute 'urlretrieve'

I am using Python 3.6 version with Anaconda. Also when i am trying to install urllib, it is saying no module called urllib.

The script working fine when i change like below.

import urllib.request
urllib.request.urlretrieve(url, filename="../enron_mail_20150507.tgz") 

Thanks

**Comment by ShengKungYi** [comment]
I get the feeling that this might be related to the Python version differences between Python 2 and Python 3? See my comment on issue #87 for more information.

**Comment by chatterjeesumit** [comment]
Hi, I am getting this error while I run the Startup.py file.
FileNotFoundError: [Errno 2] No such file or directory: 'enron_mail_20150507.tar.gz'

**Comment by rizvisharis** [comment]
Urlretrieve now exists inside urllib.request in Python 3, so your call to that function should be
urllib.request.urlretrieve(url, filename="../enron_mail_20150507.tar.gz")
Instead of just
urllib.urlretrieve(url, filename="../enron_mail_20150507.tar.gz")
