### ISSUE TITLE
print clarification

### ISSUE THREAD

**Issue by venkicnu** [udacity/ud120-projects#87]
Hi,

All udacity machine learning python scripts are using print statements in the following way.

**print "Hello World"**

But when i am executing the script, expecting parenthesis. When i run the script by modifying with parenthesis, executing successfully. May i know what might be the reason. I am using Python 3.6 with Anaconda.

Thanks

**Comment by ShengKungYi** [comment]
The course and materials were written for Python 2 and have not yet been revised to Python 3. In Python 2, `print` statements did not require parentheses surrounding the string to be printed; this functionality was later made consistent with other functions in Python 3. I believe that there are pull requests on the repo for an (as of this writing) unofficial revision of template materials for Python 3, or you can add a Python 2 environment to your Python installation to run the code as-is.
