### ISSUE TITLE
where are the emails?

### ISSUE THREAD

**Issue by paalped** [udacity/ud120-projects#94]
I don't get it, shouldn't there be folders with emails in this repository?
when I run the vectorize_text.py file I get this error: 
[Errno 2] No such file or directory: '../maildir/bailey-s/deleted_items/101.'
I check the directory one level up and there is no maildir. 

Is there something I missed?

**Comment by paalped** [comment]
got it, startup.py

**Comment by ashishkadam** [comment]
Please close this issue as it has been resolved by OP.

**Comment by Rockyyadav** [comment]
I downloaded enron_mails but I am still getting this error.

**Comment by Tiagoblima** [comment]
You have to check in your project directory if the file enron_mail_20150507.tar is unzziped. I had the same problem.

**Comment by lebaruch** [comment]
I have all the files unzipped, still same problem... I am running startup.py again, but its taking forever...

**Comment by Naincy47** [comment]
I have all the files unzipped, still same problem.

**Comment by deucer** [comment]
Trying moving the maildir folder that is created after running startup.py to the ud120-projects folder or the parent of the text_learning directory. It should be able to find it there.

**Comment by cosmos-coder** [comment]
could not convert string to float: 'maildir/bailey-s/deleted_items/101.'
getting following error while using csv file after conversion in jupyter notebook
